/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbsApp: typeof import('./components/BreadcrumbsApp.vue')['default']
    ButtonApp: typeof import('./components/ButtonApp.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    FooterApp: typeof import('./components/FooterApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarApp: typeof import('./components/SidebarApp.vue')['default']
  }
}
